# Generated by Django 4.0.4 on 2023-05-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_image',
            field=models.ImageField(default=0, upload_to='pics/'),
            preserve_default=False,
        ),
    ]
