# Generated by Django 4.0.4 on 2023-05-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0008_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('singles_image', models.ImageField(default='pics/', upload_to='')),
                ('single_file', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
