# Generated by Django 4.0.4 on 2023-05-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0009_single'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
