# Generated by Django 4.0.4 on 2023-06-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0010_alter_single_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
