# Generated by Django 4.0.4 on 2023-06-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0013_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='albumLite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='pics/')),
                ('offer', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
