# Generated by Django 4.0.4 on 2023-06-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0014_albumlite'),
    ]

    operations = [
        migrations.CreateModel(
            name='singleSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='pics/')),
                ('song', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
