# Generated by Django 4.0.4 on 2023-06-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0019_alter_event_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='pics/')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
