# Generated by Django 4.0.4 on 2023-06-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0020_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='pics/')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('day', models.IntegerField(blank=True, max_length=31, null=True)),
                ('month', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
