# Generated by Django 4.0.4 on 2023-06-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0023_alter_contact_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
