# Generated by Django 4.0.4 on 2023-06-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
