# Generated by Django 4.0.4 on 2023-06-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profiles_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='social_website',
            new_name='social_facebook',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='social_youtube',
            new_name='social_instagram',
        ),
        migrations.AddField(
            model_name='profiles',
            name='social_whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
